// This file is auto-generated by `php artisan typescript:transform`
// (composer types). Do not edit by hand.
//
// It is populated from #[TypeScript]-tagged Spatie Data DTOs and backed enums
// under app/Domain/**. No such types exist yet (foundation phase), so this stub
// is a placeholder that the transformer will overwrite once the first DTO/enum
// lands. Keeping it committed gives the frontend a stable import target.

export {};
